// packages/renderer-react/src/client.ts
import type { MountedStory, StoryArgs, StoryContext, StoryLiteStory } from '@storylite/contracts'
import type { ReactNode } from 'react'
import { createRoot, type Root } from 'react-dom/client'

export function renderStory(
  story: StoryLiteStory,
  args: StoryArgs,
  context: StoryContext,
): MountedStory {
  if (!story.render) {
    throw new Error(`React story "${story.name}" must provide a render function.`)
  }

  const mountPoint = context.document.createElement('div')
  mountPoint.className = 'sl-react-root'
  context.canvas.replaceChildren(mountPoint)

  let root: Root | null = createRoot(mountPoint, {
    onUncaughtError(error) {
      throw error
    },
  })

  root.render(story.render(args, context) as ReactNode)

  return {
    cleanup: () => {
      root?.unmount()
      root = null
      context.canvas.replaceChildren()
    },
  }
}

// packages/renderer-solid/src/client.tsx
import type { MountedStory, StoryArgs, StoryContext, StoryLiteStory } from '@storylite/contracts'
import type { Component, JSX } from 'solid-js'
import { createComponent, render } from 'solid-js/web'

export function renderStory(
  story: StoryLiteStory,
  args: StoryArgs,
  context: StoryContext,
): MountedStory {
  const mountPoint = context.document.createElement('div')
  mountPoint.className = 'sl-solid-root'
  context.canvas.replaceChildren(mountPoint)

  const dispose = render(() => resolveOutput(story, args, context), mountPoint)

  return {
    cleanup: () => {
      dispose()
      context.canvas.replaceChildren()
    },
  }
}

function resolveOutput(story: StoryLiteStory, args: StoryArgs, context: StoryContext): JSX.Element {
  if (story.render) {
    return story.render(args, context) as JSX.Element
  }

  if (typeof story.component !== 'function') {
    throw new Error(`Solid story "${story.name}" must provide a component or render function.`)
  }

  return createComponent(story.component as Component<Record<string, unknown>>, args)
}
